version: "3"

networks:
  RTB:
    driver: bridge
  RTB-connection:
    external: true

services:
  exchange:
    restart: always
    container_name: exchange
    build: 
      context: ../
      args:
        - DEFAULT_PATH=${DEFAULT_PATH}
        - CONTAINER=Exchange
    ports:
      - "${EXCHANGE_PORT}:${EXCHANGE_PORT}"
    env_file:
      - .env
    volumes:
      - "./:/usr/src/app/src"
    networks:
      - RTB
      - RTB-connection
  redis:
    image: redis:6-alpine
    restart: always
    networks:
      RTB:
        aliases:
          - "redis"
    ports:
      - 6378:6379
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - RTB
    ports:
      - 8082:8081